title: "Jekyll-Theme-MDUI"
description: "A Jekyll theme based on MDUI"
url: '' # your website url
baseurl: "" # remember do not add /
author: "mdui"
avatar: https://your.author.avatar.path.here
paginate: 5
paginate_path: "/page:num/"
headercard_left: /assets/images/jekylltheme.jpg
headercard_right:

headbar: 
   favicon: "https://ooo.0o0.ooo/2017/05/27/59294212bc16e.png" #  the website favicon
   high_res_favicon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" #  the favicon using high quality format
   apple_touch_icon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" # the iOS Home button icon
   keywords: "blog jekyll mdui theme" #  the site keywords
   theme_color: "orange" #  the color of the Chrome address bar and the navbar, indigo/red/pink/purple/deep-purple/blue/light-blue/cyan/teal/green/light-green/lime/yellow/amber/orange/deep-orange/brown/grey/blue-grey
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers

category:
   'Category.name1': 'https://category.avatar.image.url'
   'Category.name2': 'https://category.avatar.image.url'

sns_share:
   twitter: 'true'
   facebook: 'true'
   googleplus: 'true'
   weibo: 'true'
   linkedin: 'true'
   qq: 'true'
   telegram: 'true'

friends:
   - name: 'mdui官网'
     url: 'https://mdui.org'
     avatar: 'about:blank'
     desc: '这个网站的CSS！'
   - name: 'KeJun'
     url: 'https://blog.kejun.me/'
     avatar: 'https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png'
     desc: '二次元智障'

cute:
   enable: true
   live2d: false
   music: true
   music_player: aplayer
   music_netease_id: 34179273
   music_netease_type: song # song, playlist, album, search, artist

navbar:
   - name: '主页'
     url: '/'
     icon: 'home'
   - name: '标签'
     url: '/tags'
     icon: "&#xe893;"
   - name: '友情链接'
     url: '/friends'
     icon: "&#xe8a3;"

background: '' # background image

comment:
  used: "" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

plugins:
  - jekyll-paginate
  - jekyll-feed

mathjax: true

google_analytics: ""  # google analytics code

baidu_site_verification: ""  # baidu site verification code

google_site_verification: ""  # google search console verification code

baidu_auto_push: false  # if you used baidu auto push to commit links

lang: "zh"  # lang zh/en

deploy: "" # type 'coding' or 'github', your website deployer.

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
